id: I941009D2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T14:00:16+00:00'
last_modified: '2022-06-09T04:56:15.082074+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8245
  title: མིག་ཡིད་རྣ་བའི་དགའ་སྟོན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '5719':
      image_group_id: I5001
      title: ''
      total_pages: 135
      order: 1
      base_file: 5719.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
