id: P008162
initial_creation_type: ocr
source_metadata:
  id: bdr:W8245
  title: མིག་ཡིད་རྣ་བའི་དགའ་སྟོན
  author: ''
  volumes:
    8acce66bcc6b4ba0829d02d1c79086f6:
      image_group_id: I5001
      title: ''
      volume_number: 1
      total_pages: 135
ebook_metadata:
  title: མིག་ཡིད་རྣ་བའི་དགའ་སྟོན
  author: ''
  sku: P008162
  cover: cover.jpg
  layers:
  - pagination
