id: P008162
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 13:05:25.859224
source_metadata:
  id: bdr:W8245
  title: མིག་ཡིད་རྣ་བའི་དགའ་སྟོན
  author: ''
  volumes:
    8acce66bcc6b4ba0829d02d1c79086f6:
      image_group_id: I5001
      title: ''
      volume_number: 1
      total_pages: 135
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
